steps:
  - label: "deploy docs"
    command:
      - docker build --build-arg SITE_ID=$SITE_ID --build-arg NETLIFY_AUTH=$NETLIFY_AUTH . -f deploy
    agents:
      queue: "docker"
    if: build.branch == "master"

  - wait
  
  - block: "Publish package? :rocket:"

  - label: "publish"
    command:
      - npm install
      - npm run build
      - npm publish
    agents:
      queue: "node16"
    if: build.branch == "master"
