steps:
  # - label: "build"
  #   command:
  #     - docker build --build-arg SITE_ID=$SITE_ID --build-arg NETLIFY_AUTH=$NETLIFY_AUTH . -f deploy
  #   agents:
  #     queue: "docker"
  
  # - wait
  
  - label: "publish"
    command:
      - npm install
      - npm run build
      - npm run build:docs
      - npm install netlify-cli -g
      - npm publish
      - netlify deploy --site $SITE_ID  --auth $NETLIFY_AUTH  --prod
    agents:
      queue: "node16"
  