steps:
  # - label: "build"
  #   command:
  #     - docker build --build-arg SITE_ID=$SITE_ID --build-arg NETLIFY_AUTH=$NETLIFY_AUTH .
  #   agents:
  #     queue: "docker"
  
  # - wait
  
  - label: "publish"
    command:
      - npm install
      - npm run build
      - npm publish
    agents:
      queue: "node16gp"
  